//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.16 at 11:24:31 PM KST 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Applicant" type="{http://nicordesigns.com/ws/schemas}ApplicantType"/>
 *         &lt;element name="WidgetInfo" type="{http://nicordesigns.com/ws/schemas}WidgetInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicant",
    "widgetInfo"
})
@XmlRootElement(name = "InsuranceApplication")
public class InsuranceApplication {

    @XmlElement(name = "Applicant", required = true)
    protected ApplicantType applicant;
    @XmlElement(name = "WidgetInfo", required = true)
    protected WidgetInfoType widgetInfo;

    /**
     * Gets the value of the applicant property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantType }
     *     
     */
    public ApplicantType getApplicant() {
        return applicant;
    }

    /**
     * Sets the value of the applicant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantType }
     *     
     */
    public void setApplicant(ApplicantType value) {
        this.applicant = value;
    }

    /**
     * Gets the value of the widgetInfo property.
     * 
     * @return
     *     possible object is
     *     {@link WidgetInfoType }
     *     
     */
    public WidgetInfoType getWidgetInfo() {
        return widgetInfo;
    }

    /**
     * Sets the value of the widgetInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link WidgetInfoType }
     *     
     */
    public void setWidgetInfo(WidgetInfoType value) {
        this.widgetInfo = value;
    }

}
